### ISSUE TITLE
Using images

### ISSUE THREAD

**Issue by yannjor** [JaxsonYehNah/pkmnmap#3]
Hey @JaxsonYehNah,

Awesome project! Just wondering, is it okay if I use the [FR&LG Kanto map](https://github.com/JaxsonYehNah/pkmnmap/blob/main/FireRedLeafGreen/Untiled/Pokemon-FireRed%26LeafGreenVersions-Kanto.png) for my own open source project? I can of course add attribution to your work.

**Comment by JaxsonYehNah** [comment]
Yer go ahead, pulled these from the rom itself. but they are identical to the ones supplied on bulb

**Comment by yannjor** [comment]
Oh nice, out of curiosity, how did you combine them into one map? Or were you able to pull the whole map from the ROM?

**Comment by JaxsonYehNah** [comment]
just photoshop, was able to create a grid and line up all the routes from there.
